// Barrel re-export for backward compatibility
export {
  // Media query
  mediaKeys,
  useMediaList,
  useInfiniteMediaList,
  useMediaAlphabet,
  useMedia,
  useMediaWithFiles,
  // Series
  seriesKeys,
  useSeriesList,
  useInfiniteSeriesList,
  useSeriesAlphabet,
  useSeriesDetail,
  useSeriesSearch,
  useSeasons,
  useEpisodes,
  useEpisode,
  // Playback
  streamingKeys,
  useStreamUrls,
  useSubtitles,
  useAudioTracks,
  usePlaybackInfo,
  useStreamUrl,
  // Progress
  userDataKeys,
  useProgress,
  useUpdateProgress,
  useFavorites,
  useInfiniteFavorites,
  useFavoritesAlphabet,
  useToggleFavorite,
  useRecentlyWatched,
  // Continue watching
  continueWatchingKeys,
  nextUpKeys,
  useContinueWatching,
  useNextUp,
  useDismissProgress,
  // Subtitle ops
  subtitleSearchKeys,
  useSubtitleSearch,
  useDownloadSubtitle,
  useAutoDownloadSubtitle,
  useTranslateSubtitle,
  // Metadata ops
  useRefreshMetadata,
  useDownloadToNas,
  useRemoveDownloadFromNas,
  useDownloadSeriesToNas,
  useRemoveSeriesDownloadFromNas,
  useCloudProbe,
  useEditMediaMetadata,
  useEditSeriesMetadata,
  useUploadMediaImage,
  useUploadSeriesImage,
  useUnlockMetadata,
  useEditEpisodeMetadata,
  // Genres
  useAllGenres,
  useMediaGenres,
  useMediaCredits,
  useSeriesGenres,
  useSeriesCredits,
  searchKeys,
  useSearch,
  useGenres,
  browseKeys,
  useFolderBrowse,
  // Library
  useFsBrowse,
  libraryKeys,
  useLibraries,
  useCreateLibrary,
  useDeleteLibrary,
  useScanLibrary,
} from '@velox/shared/hooks/media'
